package com.vaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Link;
import com.vaadin.ui.Label;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Button;
import com.vaadin.ui.VerticalSplitPanel;
import com.vaadin.ui.CssLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainPageDesign extends VerticalLayout {
    protected HorizontalLayout header;
    protected ComboBox<org.vaadin.bugrap.domain.entities.Project> projectSelectorCombo;
    protected Label accountNameLabel;
    protected Link logoutLink;
    protected HorizontalLayout menu;
    protected Link reportBugLink;
    protected Link requestFeatureLink;
    protected Link manageProjectLink;
    protected HorizontalLayout searchReportLayout;
    protected Label searchIconLabel;
    protected TextField searchField;
    protected Label searchCloseLabel;
    protected HorizontalLayout reportsDetails;
    protected ComboBox<org.vaadin.bugrap.domain.entities.ProjectVersion> projectVersionsCombo;
    protected HorizontalLayout projectProgressContainer;
    protected HorizontalLayout reportsFiltering;
    protected CssLayout assigneesOptions;
    protected Button everyoneAssigneeBtn;
    protected Button onlyMeAssigneeBtn;
    protected CssLayout statusOptions;
    protected Button allKindsStatusBtn;
    protected Button openStatusBtn;
    protected VerticalSplitPanel tableDetailsSession;

    public MainPageDesign() {
        Design.read(this);
    }
}
