package com.vaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Link;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ReportsDetailDesign extends VerticalLayout {
    protected HorizontalLayout oneItemSelectedTitleContainer;
    protected Link newWindowLink;
    protected HorizontalLayout multipleItemsSelectedTitleContainer;
    protected HorizontalLayout updateReportFormContainer;
    protected ComboBox<String> priorityCombo;
    protected ComboBox<String> typeCombro;
    protected ComboBox<String> statusCombo;
    protected ComboBox<String> assignedToCombo;
    protected ComboBox<String> versionCombo;
    protected Button updateReportsBtn;
    protected Button revertReportsBtn;

    public ReportsDetailDesign() {
        Design.read(this);
    }


}
